# frozen_string_literal: true

plugins:
  - rubocop-performance
  - rubocop-minitest
  - rubocop-thread_safety

inherit_gem:
  standard: config/base.yml
  standard-performance: config/base.yml
  standard-minitest: config/base.yml

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2
  Include:
    - "**/*.rb"
    - "**/*.gemspec"
    - "**/Gemfile"
    - "**/Rakefile"
    - Gemfile.lint

# Layout
Layout/LineLength:
  Max: 100

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: space

# Gemspec
Gemspec/DuplicatedAssignment:
  Enabled: false

# Lint
Lint/AssignmentInCondition:
  Enabled: false

Lint/ConstantDefinitionInBlock:
  Enabled: false

Lint/EnsureReturn:
  Enabled: false

Lint/IneffectiveAccessModifier:
  Enabled: false

Lint/NonLocalExitFromIterator:
  Enabled: false

Lint/RescueException:
  Exclude:
    - lib/rdkafka/admin.rb
    - lib/rdkafka/bindings.rb

# Security
Security/Open:
  Exclude:
    - ext/Rakefile

# Style
Style/GlobalVars:
  Enabled: false

# ThreadSafety
ThreadSafety/ClassAndModuleAttributes:
  Enabled: false

ThreadSafety/ClassInstanceVariable:
  Enabled: false

ThreadSafety/NewThread:
  Enabled: false

# Minitest
Minitest/MultipleAssertions:
  Enabled: false

Minitest/AssertionInLifecycleHook:
  Enabled: false

Minitest/AssertRaisesCompoundBody:
  Enabled: false
