# CI Strategy: Comprehensive Testing of Build and Precompiled Flows
#
# This workflow tests both compilation-from-source and precompiled binary distribution
# strategies across multiple Ubuntu and Ruby versions to ensure broad compatibility and
# reliability.
#
# WHY WE TEST BOTH UBUNTU 22.04 AND 24.04:
# - Different system library versions (OpenSSL, zlib, libsasl2, libzstd, etc.)
# - Different GCC compiler versions that affect native extension compilation
# - Different glibc versions that can impact binary compatibility
# - Real-world deployment scenarios where users run on various Ubuntu LTS versions
# - Different Ruby versions
#
# COMPILATION FLOW (build_install + specs_install):
# - Tests that librdkafka compiles correctly from source on each Ubuntu version
# - Validates that mini_portile2 can successfully build native dependencies
# - Ensures Ruby native extensions link properly with system libraries
# - Verifies that the same codebase works across different toolchain versions
#
# PRECOMPILED FLOW (build_precompiled + specs_precompiled):
# - Tests our precompiled static libraries work on different Ubuntu versions
# - Validates that statically-linked binaries are truly portable across environments
# - Ensures precompiled libraries don't have unexpected system dependencies
# - Verifies that removing build tools doesn't break precompiled binary usage
#
# ARTIFACT ISOLATION:
# - Each Ubuntu version gets separate artifacts (rdkafka-built-gem-22.04, etc.)
# - Prevents cross-contamination of OS-specific compiled extensions
# - Ensures test accuracy by matching build and test environments
#
# This comprehensive approach catches issues that single-platform testing would miss,
# such as system library incompatibilities, compiler-specific bugs, or static linking
# problems that only manifest on specific Ubuntu versions.

name: CI Linux aarch64 GNU

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    branches: [ main, master ]
  push:
    branches: [ main, master ]
  schedule:
    - cron: '0 4 * * *'

permissions:
  contents: read

env:
  BUNDLE_RETRY: 6
  BUNDLE_JOBS: 4

jobs:
  specs_install:
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - '3.5.0-preview1'
          - '3.4'
          - '3.3'
          - '3.2'
          - '3.1'
          - 'jruby-10.0'
        ubuntu-version: ['22.04', '24.04']
        include:
          - ruby: '3.4'
            coverage: 'true'
          - ruby: 'jruby-10.0'
            continue-on-error: true
    runs-on: ubuntu-${{ matrix.ubuntu-version }}-arm
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0
      - name: Set up Ruby
        uses: ruby/setup-ruby@2a7b30092b0caf9c046252510f9273b4875f3db9 # v1.254.0
        with:
          ruby-version: ${{matrix.ruby}}
          bundler-cache: false
      - name: Start Kafka with Docker Compose
        run: |
          docker compose up -d
          echo "Waiting for Kafka to be ready..."

          sleep 10

          echo "=== Container status ==="
          docker compose ps kafka

          for i in {1..30}; do
            echo "=== Attempt $i/30 ==="

            echo "Testing kafka-topics command..."
            if docker compose exec -T kafka kafka-topics --bootstrap-server localhost:9092 --list >/dev/null 2>&1; then
              echo "Kafka topics command succeeded!"
              break
            else
              echo "Kafka topics command failed (exit code: $?)"
            fi

            echo "Sleeping 2 seconds..."
            sleep 2
          done
      - name: Install dependencies
        env:
          RDKAFKA_EXT_PATH: ${{ github.workspace }}/ext
        run: |
          # Only install gems that aren't Ruby-version specific
          bundle install
      - name: Build gem with mini_portile
        run: |
          set -e
          cd ext && bundle exec rake
          cd ..
      - name: Run all specs
        env:
          GITHUB_COVERAGE: ${{matrix.coverage}}
          RDKAFKA_EXT_PATH: ${{ github.workspace }}/ext
        continue-on-error: ${{ matrix.continue-on-error || false }}
        run: |
          bundle exec rspec

  build_precompiled:
    timeout-minutes: 30
    # We precompile on older Ubuntu and check compatibility by running specs since we aim to
    # release only one precompiled version for all supported Ubuntu versions
    # This is why we do not want Renovate to update it automatically
    runs-on: ubuntu-22.04-arm # renovate: ignore
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0
      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            build-essential \
            gcc \
            g++ \
            make \
            tar \
            gzip \
            wget \
            curl \
            file \
            pkg-config \
            autoconf \
            automake \
            libtool \
            python3 \
            git \
            ca-certificates \
            patch \
            libsasl2-dev \
            libssl-dev \
            zlib1g-dev \
            libzstd-dev \
            bison \
            flex \
            perl \
            binutils-dev
      - name: Cache build-tmp directory
        uses: actions/cache@0400d5f644dc74513175e3cd8d07132dd4860809 # v4.2.4
        with:
          path: ext/build-tmp
          key: build-tmp-${{ runner.os }}-${{ hashFiles('ext/*.sh', 'ext/Rakefile') }}-v2
      - name: Build precompiled librdkafka.so
        run: |
          cd ext
          ./build_linux_aarch64_gnu.sh
      - name: Upload precompiled library
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: librdkafka-precompiled-linux
          path: ext/
          retention-days: 1

  specs_precompiled:
    timeout-minutes: 30
    needs: build_precompiled
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - '3.5.0-preview1'
          - '3.4'
          - '3.3'
          - '3.2'
          - '3.1'
        ubuntu-version: ['22.04', '24.04']
        include:
          - ruby: '3.4'
            ubuntu-version: '24.04'
            coverage: 'true'

    runs-on: ubuntu-${{ matrix.ubuntu-version }}-arm
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0
      - name: Download precompiled library
        uses: actions/download-artifact@634f93cb2916e3fdff6788551b99b062d0335ce0 # v5.0.0
        with:
          name: librdkafka-precompiled-linux
          path: ext/
      - name: Set up Ruby
        uses: ruby/setup-ruby@2a7b30092b0caf9c046252510f9273b4875f3db9 # v1.254.0
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: false
      - name: Start Kafka with Docker Compose
        run: |
          docker compose up -d
          echo "Waiting for Kafka to be ready..."

          sleep 10

          echo "=== Container status ==="
          docker compose ps kafka
          for i in {1..30}; do
            echo "=== Attempt $i/30 ==="

            echo "Testing kafka-topics command..."
            if docker compose exec -T kafka kafka-topics --bootstrap-server localhost:9092 --list >/dev/null 2>&1; then
              echo "Kafka topics command succeeded!"
              break
            else
              echo "Kafka topics command failed (exit code: $?)"
            fi

            echo "Sleeping 2 seconds..."
            sleep 2
          done
      - name: Install bundle with precompiled library
        env:
          GITHUB_COVERAGE: ${{ matrix.coverage }}
          RDKAFKA_EXT_PATH: ${{ github.workspace }}/ext
        run: |
          bundle install
          echo "Bundle install completed with precompiled library"
      - name: Remove build dependencies to test static linking
        continue-on-error: true
        run: |
          echo "Removing build dependencies to verify precompiled library is truly self-contained..."

          # Remove packages one by one to avoid dependency conflicts
          packages_to_remove="build-essential gcc g++ make patch tar wget libsasl2-dev libssl-dev zlib1g-dev libzstd-dev"

          for package in $packages_to_remove; do
            if dpkg -l | grep -q "^ii.*$package "; then
              echo "Removing $package..."
              sudo dpkg --remove --force-depends $package 2>/dev/null || echo "Could not remove $package"
            else
              echo "$package is not installed"
            fi
          done

          echo "Build dependencies removal completed"
          echo "Remaining build tools:"
          which gcc g++ make 2>/dev/null || echo "No build tools found in PATH (good!)"
      - name: Run specs with precompiled library
        env:
          GITHUB_COVERAGE: ${{ matrix.coverage }}
          RDKAFKA_EXT_PATH: ${{ github.workspace }}/ext
        run: |
          bundle exec rspec
